name: Build and Release Datasets
on:
  release:
    types: [created]

jobs:
  generate:
    name: Build Dataset Archives
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘€ Checkout
        users: actions/checkout@v2
      - name: ğŸ—ï¸ Generate Artifacts
        run: |
          bash zip_artifacts.sh
      - name: ğŸ“¤ Upload Artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/*.zip'
