name: Build and Release Datasets
on:
  release:
    types: [created]

jobs:
  generate:
    name: Build Dataset Archives
    runs-on: ubuntu-latest
    steps:

      - name: ğŸ‘€ Checkout
        uses: actions/checkout@v2

      - name: ğŸ”– Get Release Tag
        id: latesttag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: ğŸ—ï¸ Generate Artifacts
        env:
          RELEASE_VERSION: ${{ steps.latesttag.output.tag }}
        run: bash zip_artifacts.sh

      - name: ğŸ“¤ Upload Artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/*.zip'
